[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
startCommand = ""
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
