spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/project-db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 900000  # 15 минут в миллисекундах
  refresh-expiration: 604800000  # 7 дней в миллисекундах

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}